import { PrismaClient, FundingLevel, StudyLevel, ScholarshipStatus } from '@prisma/client';
import bcrypt from 'bcryptjs';

const db = new PrismaClient();

// Development-only seed credentials — never used for real curation.
const DEV_ADMIN_EMAIL = 'admin@bursa.dev';
const DEV_ADMIN_PASSWORD = 'DevAdmin123!';

const now = new Date();
const days = (n: number) => new Date(now.getTime() + n * 24 * 60 * 60 * 1000);

type SeedRow = {
  title: string;
  slug: string;
  provider: string;
  officialUrl: string;
  fundingLevel: FundingLevel;
  studyLevels: StudyLevel[];
  fieldsOfStudy: string[];
  hostCountry: string;
  region: string;
  eligibleNationalities: string[];
  openToAllAfrican: boolean;
  benefits: string;
  eligibility: string;
  requirements: string;
  deadlineAt: Date | null;
  status: ScholarshipStatus;
  source: string;
  verifiedAt: Date | null;
};

// Hand-authored, not templated, so the demo data reads like a real catalog
// rather than obviously generated filler. This is seed/demo data only —
// Bursa's discovery-layer framing (elsewhere in the product) already makes
// clear that a listing is a starting point, not a guarantee.
const scholarships: SeedRow[] = [
  {
    title: 'Mastercard Foundation Scholars Program',
    slug: 'mastercard-foundation-scholars-program',
    provider: 'Mastercard Foundation',
    officialUrl: 'https://mastercardfdn.org/en/what-we-do/programs/young-people-and-education/scholars-program/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Rwanda',
    region: 'East Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Full tuition, accommodation, living stipend, mentorship, and leadership development.',
    eligibility: 'Open to academically talented African students demonstrating leadership potential and financial need.',
    requirements: 'Academic transcripts, two reference letters, personal statement, proof of financial need.',
    deadlineAt: days(45),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Mastercard Foundation official site',
    verifiedAt: now,
  },
  {
    title: "DAAD Master's Scholarship for Engineering",
    slug: 'daad-masters-scholarship-engineering',
    provider: 'German Academic Exchange Service (DAAD)',
    officialUrl: 'https://www.daad.de/en/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Engineering', 'Computer Science'],
    hostCountry: 'Germany',
    region: 'Europe',
    eligibleNationalities: ['Nigeria', 'Kenya', 'Ghana', 'Egypt'],
    openToAllAfrican: false,
    benefits: 'Monthly stipend, travel allowance, health insurance, tuition waiver.',
    eligibility: "Applicants must hold a bachelor's degree in engineering or a related field with at least two years of professional experience.",
    requirements: "Bachelor's certificate, CV, motivation letter, two academic references, language certificate.",
    deadlineAt: days(12),
    status: ScholarshipStatus.PUBLISHED,
    source: 'DAAD official site',
    verifiedAt: now,
  },
  {
    title: 'Chevening Scholarship',
    slug: 'chevening-scholarship',
    provider: 'UK Government (FCDO)',
    officialUrl: 'https://www.chevening.org/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition fees, monthly stipend, travel costs, arrival and departure allowances.',
    eligibility: 'At least two years of work experience and a completed undergraduate degree; must return to home country for two years after the award.',
    requirements: 'Three essays, two references, English proficiency test, three UK university course choices.',
    deadlineAt: days(-10),
    status: ScholarshipStatus.CLOSED,
    source: 'Chevening official site',
    verifiedAt: now,
  },
  {
    title: 'African Union PhD Research Grant',
    slug: 'african-union-phd-research-grant',
    provider: 'African Union Commission',
    officialUrl: 'https://au.int/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Public Health', 'Agriculture', 'Environmental Science'],
    hostCountry: 'South Africa',
    region: 'Southern Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Research grant covering fieldwork and materials; tuition not included.',
    eligibility: 'Enrolled PhD candidates researching topics relevant to African development priorities.',
    requirements: 'Research proposal, supervisor endorsement letter, institutional enrollment confirmation.',
    deadlineAt: days(90),
    status: ScholarshipStatus.PUBLISHED,
    source: 'African Union official site',
    verifiedAt: now,
  },
  {
    title: 'Ghana Tertiary Education Trust Fund Stipend',
    slug: 'ghana-getfund-stipend',
    provider: 'Ghana Education Trust Fund',
    officialUrl: 'https://getfund.gov.gh/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Ghana',
    region: 'West Africa',
    eligibleNationalities: ['Ghana'],
    openToAllAfrican: false,
    benefits: 'Monthly living stipend for the academic year; tuition not covered.',
    eligibility: 'Ghanaian nationals enrolled full-time in an accredited public tertiary institution.',
    requirements: 'Admission letter, national ID, guardian income declaration.',
    deadlineAt: days(3),
    status: ScholarshipStatus.PUBLISHED,
    source: 'GETFund official site',
    verifiedAt: now,
  },
  {
    title: 'Toyota Foundation Tuition-Only Award',
    slug: 'toyota-foundation-tuition-only-award',
    provider: 'Toyota Foundation',
    officialUrl: 'https://www.toyotafound.or.jp/english/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Automotive Engineering', 'Manufacturing'],
    hostCountry: 'Japan',
    region: 'Asia',
    eligibleNationalities: ['Kenya', 'Nigeria', 'South Africa'],
    openToAllAfrican: false,
    benefits: 'Full tuition waiver; living costs and travel not covered.',
    eligibility: 'Applicants must be enrolled or admitted to an accredited engineering program.',
    requirements: 'Admission letter, academic transcripts, statement of purpose.',
    deadlineAt: null,
    status: ScholarshipStatus.DRAFT,
    source: 'Toyota Foundation official site',
    verifiedAt: null,
  },
  {
    title: 'Nigerian Petroleum Technology Development Fund Overseas Scholarship',
    slug: 'ptdf-overseas-scholarship',
    provider: 'Petroleum Technology Development Fund (PTDF)',
    officialUrl: 'https://ptdf.gov.ng/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Engineering', 'Natural Sciences'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: ['Nigeria'],
    openToAllAfrican: false,
    benefits: 'Tuition, monthly upkeep allowance, return airfare, and book allowance.',
    eligibility: 'Nigerian citizens with a first degree in engineering, geosciences, or a related technical field.',
    requirements: 'Degree certificate, NYSC certificate, two referee reports, PTDF aptitude test.',
    deadlineAt: days(60),
    status: ScholarshipStatus.PUBLISHED,
    source: 'PTDF official site',
    verifiedAt: now,
  },
  {
    title: 'Kenya National Government CDF Bursary',
    slug: 'kenya-cdf-bursary',
    provider: 'Kenya Constituency Development Fund',
    officialUrl: 'https://cdf.go.ke/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Kenya',
    region: 'East Africa',
    eligibleNationalities: ['Kenya'],
    openToAllAfrican: false,
    benefits: 'Termly bursary contribution toward tuition and boarding fees.',
    eligibility: 'Kenyan students from the sponsoring constituency demonstrating financial need.',
    requirements: 'Fee structure from institution, chief’s letter, parent/guardian ID.',
    deadlineAt: days(21),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Constituency Development Fund Board',
    verifiedAt: now,
  },
  {
    title: 'University of Cape Town Postgraduate Merit Award',
    slug: 'uct-postgraduate-merit-award',
    provider: 'University of Cape Town',
    officialUrl: 'https://www.uct.ac.za/main/apply/funding',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'South Africa',
    region: 'Southern Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Partial tuition remission based on prior academic performance.',
    eligibility: 'Applicants with a first-class or upper-second-class undergraduate degree.',
    requirements: 'Academic transcript, admission offer, motivation letter.',
    deadlineAt: days(150),
    status: ScholarshipStatus.PUBLISHED,
    source: 'UCT Postgraduate Funding Office',
    verifiedAt: now,
  },
  {
    title: 'Ethiopian Ministry of Education Undergraduate Grant',
    slug: 'ethiopia-moe-undergraduate-grant',
    provider: 'Ethiopian Ministry of Education',
    officialUrl: 'https://www.moe.gov.et/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Education', 'Natural Sciences'],
    hostCountry: 'Ethiopia',
    region: 'East Africa',
    eligibleNationalities: ['Ethiopia'],
    openToAllAfrican: false,
    benefits: 'Full tuition waiver at public universities for qualifying fields.',
    eligibility: 'Ethiopian secondary school graduates meeting the national university entrance cutoff.',
    requirements: 'National exam results, kebele ID, admission letter.',
    deadlineAt: days(-30),
    status: ScholarshipStatus.CLOSED,
    source: 'Ministry of Education official site',
    verifiedAt: now,
  },
  {
    title: 'Fulbright Foreign Student Program',
    slug: 'fulbright-foreign-student-program',
    provider: 'U.S. Department of State',
    officialUrl: 'https://foreign.fulbrightonline.org/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United States',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, airfare, living stipend, and health insurance for the length of the program.',
    eligibility: 'Bachelor’s degree completed, strong English proficiency, intent to return home after the program.',
    requirements: 'TOEFL/IELTS score, academic transcripts, three recommendation letters, study objective statement.',
    deadlineAt: days(75),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Fulbright official site',
    verifiedAt: now,
  },
  {
    title: 'Australia Awards Africa Scholarship',
    slug: 'australia-awards-africa',
    provider: 'Australian Government (DFAT)',
    officialUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Public Health', 'Agriculture', 'Economics'],
    hostCountry: 'Australia',
    region: 'Oceania',
    eligibleNationalities: ['Kenya', 'Ghana', 'Ethiopia', 'Nigeria', 'Rwanda'],
    openToAllAfrican: false,
    benefits: 'Full tuition, return airfare, establishment allowance, and monthly stipend.',
    eligibility: 'At least two years of relevant work experience in a development-priority sector.',
    requirements: 'Employer endorsement, academic transcripts, English test, development impact statement.',
    deadlineAt: days(38),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Australia Awards official site',
    verifiedAt: now,
  },
  {
    title: 'Netherlands Orange Knowledge Programme',
    slug: 'netherlands-orange-knowledge-programme',
    provider: 'Nuffic',
    officialUrl: 'https://www.nuffic.nl/en/subjects/orange-knowledge-programme',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Water Management', 'Agriculture', 'Law'],
    hostCountry: 'Netherlands',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, monthly allowance, visa costs, and health insurance.',
    eligibility: 'Mid-career professionals from an approved list of countries with at least three years of work experience.',
    requirements: 'Employer letter, CV, motivation letter, English proficiency proof.',
    deadlineAt: days(100),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Nuffic official site',
    verifiedAt: now,
  },
  {
    title: 'Canada Queen Elizabeth II Diamond Jubilee Scholarship',
    slug: 'canada-qes-scholarship',
    provider: 'Universities Canada',
    officialUrl: 'https://qes.mastercardfdn.org/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Canada',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, travel, and living costs for a study or exchange term in Canada.',
    eligibility: 'Enrolled students nominated by a partner university under the exchange agreement.',
    requirements: 'Home university nomination, transcript, statement of intent.',
    deadlineAt: days(55),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Universities Canada official site',
    verifiedAt: now,
  },
  {
    title: 'Rhodes Scholarship for Africa',
    slug: 'rhodes-scholarship-africa',
    provider: 'Rhodes Trust',
    officialUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: ['Nigeria', 'Kenya', 'South Africa', 'Ghana', 'Zambia', 'Zimbabwe'],
    openToAllAfrican: false,
    benefits: 'Full tuition at the University of Oxford, living stipend, and travel costs.',
    eligibility: 'Outstanding academic record combined with demonstrated leadership and service.',
    requirements: 'Academic transcripts, five to eight references, personal statement, interview.',
    deadlineAt: days(120),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Rhodes Trust official site',
    verifiedAt: now,
  },
  {
    title: 'Schwarzman Scholars Program',
    slug: 'schwarzman-scholars-program',
    provider: 'Schwarzman Scholars',
    officialUrl: 'https://www.schwarzmanscholars.org/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Business', 'Economics', 'Public Policy'],
    hostCountry: 'China',
    region: 'Asia',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, room and board, travel, and a personal stipend for a one-year master’s at Tsinghua University.',
    eligibility: 'Bachelor’s degree holders aged 18 to 29 with demonstrated leadership potential.',
    requirements: 'Transcripts, three recommendation letters, two essays, video statement, interview.',
    deadlineAt: days(80),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Schwarzman Scholars official site',
    verifiedAt: now,
  },
  {
    title: 'Erasmus Mundus Joint Master Degree Scholarship',
    slug: 'erasmus-mundus-joint-master',
    provider: 'European Commission',
    officialUrl: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Data Science', 'Environmental Science', 'Economics'],
    hostCountry: 'France',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, travel allowance, installation costs, and a monthly subsistence allowance.',
    eligibility: 'Completed bachelor’s degree; each joint programme sets its own specific entry requirements.',
    requirements: 'Programme-specific application, transcripts, language certificate, references.',
    deadlineAt: days(200),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Erasmus Mundus catalogue',
    verifiedAt: now,
  },
  {
    title: 'Islamic Development Bank Merit Scholarship',
    slug: 'isdb-merit-scholarship',
    provider: 'Islamic Development Bank',
    officialUrl: 'https://www.isdb.org/isdb-scholarships',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Engineering', 'Natural Sciences', 'Medicine'],
    hostCountry: 'United Arab Emirates',
    region: 'Middle East',
    eligibleNationalities: ['Nigeria', 'Egypt', 'Senegal', 'Morocco', 'Tunisia', 'Algeria'],
    openToAllAfrican: false,
    benefits: 'Tuition fees, monthly stipend, and round-trip airfare.',
    eligibility: 'Nationals of IsDB member countries with a strong academic record in science or technology fields.',
    requirements: 'Academic transcripts, admission letter, two references, IsDB scholarship exam.',
    deadlineAt: days(9),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Islamic Development Bank official site',
    verifiedAt: now,
  },
  {
    title: 'Japan MEXT Scholarship for African Students',
    slug: 'japan-mext-scholarship-africa',
    provider: 'Japanese Ministry of Education (MEXT)',
    officialUrl: 'https://www.studyinjapan.go.jp/en/planning/scholarship/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Japan',
    region: 'Asia',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, monthly stipend, and round-trip airfare to Japan.',
    eligibility: 'Applicants apply through their country’s Japanese embassy; age and academic requirements vary by category.',
    requirements: 'Embassy application form, transcripts, health certificate, embassy interview.',
    deadlineAt: days(64),
    status: ScholarshipStatus.PUBLISHED,
    source: 'MEXT official site',
    verifiedAt: now,
  },
  {
    title: 'South Korea Global Korea Scholarship',
    slug: 'south-korea-global-korea-scholarship',
    provider: 'National Institute for International Education (Korea)',
    officialUrl: 'https://www.studyinkorea.go.kr/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'South Korea',
    region: 'Asia',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, monthly living allowance, one year of Korean language training, and settlement allowance.',
    eligibility: 'Applicants under 25 (undergraduate) or 40 (graduate) with a strong academic record.',
    requirements: 'Academic transcripts, statement of purpose, embassy or university nomination.',
    deadlineAt: days(48),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Study in Korea official site',
    verifiedAt: now,
  },
  {
    title: 'Commonwealth Shared Scholarship',
    slug: 'commonwealth-shared-scholarship',
    provider: 'Commonwealth Scholarship Commission',
    officialUrl: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition fees, airfare, and a stipend for a taught master’s at a UK university.',
    eligibility: 'Citizens of least-developed Commonwealth countries who could not otherwise afford UK study.',
    requirements: 'University application, transcripts, two references, development impact statement.',
    deadlineAt: days(28),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Commonwealth Scholarship Commission',
    verifiedAt: now,
  },
  {
    title: 'World Bank Graduate Scholarship Program',
    slug: 'world-bank-graduate-scholarship',
    provider: 'World Bank Group',
    officialUrl: 'https://www.worldbank.org/en/programs/scholarships',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Economics', 'Public Policy', 'Environmental Studies'],
    hostCountry: 'United States',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, monthly living allowance, and travel to and from the host institution.',
    eligibility: 'At least three years of recent development-related work experience.',
    requirements: 'Employer reference, admission to a partner university, development-focus essay.',
    deadlineAt: days(140),
    status: ScholarshipStatus.PUBLISHED,
    source: 'World Bank official site',
    verifiedAt: now,
  },
  {
    title: 'African Development Bank Excellence Scholarship',
    slug: 'afdb-excellence-scholarship',
    provider: 'African Development Bank',
    officialUrl: 'https://www.afdb.org/en/about/careers/afdb-scholarship-program',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Economics', 'Engineering', 'Environmental Studies'],
    hostCountry: 'Cote d’Ivoire',
    region: 'West Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Partial tuition support and a contribution toward living costs.',
    eligibility: 'Citizens of AfDB regional member countries admitted to a qualifying master’s program.',
    requirements: 'Admission letter, transcripts, statement of development relevance.',
    deadlineAt: days(6),
    status: ScholarshipStatus.PUBLISHED,
    source: 'African Development Bank official site',
    verifiedAt: now,
  },
  {
    title: 'Zambia Higher Education Loans and Scholarships Board Award',
    slug: 'zambia-heslb-award',
    provider: 'Higher Education Loans and Scholarships Board (Zambia)',
    officialUrl: 'https://www.heslb.co.zm/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Medicine', 'Engineering', 'Education'],
    hostCountry: 'Zambia',
    region: 'Southern Africa',
    eligibleNationalities: ['Zambia'],
    openToAllAfrican: false,
    benefits: 'Loan-scholarship hybrid covering tuition and a portion of upkeep costs.',
    eligibility: 'Zambian citizens admitted to a public university in a priority field.',
    requirements: 'Admission letter, national registration card, means-testing form.',
    deadlineAt: days(15),
    status: ScholarshipStatus.PUBLISHED,
    source: 'HESLB official site',
    verifiedAt: now,
  },
  {
    title: 'Botswana Ministry of Tertiary Education Sponsorship',
    slug: 'botswana-mote-sponsorship',
    provider: 'Botswana Ministry of Tertiary Education',
    officialUrl: 'https://www.mote.gov.bw/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Botswana',
    region: 'Southern Africa',
    eligibleNationalities: ['Botswana'],
    openToAllAfrican: false,
    benefits: 'Full tuition, boarding, and a monthly allowance for local study.',
    eligibility: 'Botswana citizens who have met the admission requirements of a local public institution.',
    requirements: 'Omang (national ID), admission letter, academic transcripts.',
    deadlineAt: days(-5),
    status: ScholarshipStatus.CLOSED,
    source: 'Ministry of Tertiary Education official site',
    verifiedAt: now,
  },
  {
    title: 'Namibia Students Financial Assistance Fund Grant',
    slug: 'namibia-nsfaf-grant',
    provider: 'Namibia Students Financial Assistance Fund',
    officialUrl: 'https://nsfaf.na/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Namibia',
    region: 'Southern Africa',
    eligibleNationalities: ['Namibia'],
    openToAllAfrican: false,
    benefits: 'Living allowance and a book allowance for the academic year.',
    eligibility: 'Namibian citizens enrolled at an accredited institution demonstrating financial need.',
    requirements: 'Means test, admission letter, national ID.',
    deadlineAt: days(19),
    status: ScholarshipStatus.PUBLISHED,
    source: 'NSFAF official site',
    verifiedAt: now,
  },
  {
    title: 'Morocco Excellence Scholarship for Engineering Sciences',
    slug: 'morocco-excellence-engineering',
    provider: 'Moroccan Ministry of Higher Education',
    officialUrl: 'https://www.enssup.gov.ma/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Engineering'],
    hostCountry: 'Morocco',
    region: 'North Africa',
    eligibleNationalities: ['Morocco'],
    openToAllAfrican: false,
    benefits: 'Partial tuition support at a national engineering school.',
    eligibility: 'Moroccan students ranking in the top tier of the national engineering entrance exam.',
    requirements: 'Entrance exam results, transcripts, admission confirmation.',
    deadlineAt: days(33),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Senegal Bourse d’Excellence Nationale',
    slug: 'senegal-bourse-excellence-nationale',
    provider: 'Senegalese Ministry of Higher Education',
    officialUrl: 'https://www.mesr.gouv.sn/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Senegal',
    region: 'West Africa',
    eligibleNationalities: ['Senegal'],
    openToAllAfrican: false,
    benefits: 'Tuition waiver at public universities for top baccalaureate performers.',
    eligibility: 'Senegalese students with distinction-level results in the national baccalaureate.',
    requirements: 'Baccalaureate results, national ID, university admission confirmation.',
    deadlineAt: days(41),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Cameroon National Merit Scholarship',
    slug: 'cameroon-national-merit-scholarship',
    provider: 'Cameroonian Ministry of Higher Education',
    officialUrl: 'https://www.minesup.gov.cm/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Cameroon',
    region: 'Central Africa',
    eligibleNationalities: ['Cameroon'],
    openToAllAfrican: false,
    benefits: 'Annual merit stipend paid directly to top-ranking students per faculty.',
    eligibility: 'Cameroonian nationals ranked among the top of their faculty cohort.',
    requirements: 'Faculty ranking letter, national ID, bank account details.',
    deadlineAt: days(70),
    status: ScholarshipStatus.PUBLISHED,
    source: 'MINESUP official site',
    verifiedAt: now,
  },
  {
    title: 'Zimbabwe Presidential Scholarship Scheme',
    slug: 'zimbabwe-presidential-scholarship',
    provider: 'Zimbabwe Ministry of Higher and Tertiary Education',
    officialUrl: 'https://www.mhtestd.gov.zw/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Medicine', 'Engineering', 'Natural Sciences'],
    hostCountry: 'Zimbabwe',
    region: 'Southern Africa',
    eligibleNationalities: ['Zimbabwe'],
    openToAllAfrican: false,
    benefits: 'Full tuition and a living allowance for STEM and health-sciences students.',
    eligibility: 'Zimbabwean nationals with strong A-level results in science subjects.',
    requirements: 'A-level results, admission letter, national registration.',
    deadlineAt: days(-2),
    status: ScholarshipStatus.CLOSED,
    source: 'Ministry of Higher and Tertiary Education',
    verifiedAt: now,
  },
  {
    title: 'Tunisia Excellence Grant for Doctoral Research',
    slug: 'tunisia-excellence-doctoral-grant',
    provider: 'Tunisian Ministry of Higher Education and Scientific Research',
    officialUrl: 'https://www.mesrs.tn/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Natural Sciences', 'Mathematics'],
    hostCountry: 'Tunisia',
    region: 'North Africa',
    eligibleNationalities: ['Tunisia'],
    openToAllAfrican: false,
    benefits: 'Monthly doctoral research stipend; tuition not applicable at public institutions.',
    eligibility: 'Enrolled doctoral candidates with an approved thesis supervisor.',
    requirements: 'Thesis proposal, supervisor letter, enrollment certificate.',
    deadlineAt: days(85),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Algeria National Scientific Research Scholarship',
    slug: 'algeria-national-scientific-research',
    provider: 'Algerian Ministry of Higher Education',
    officialUrl: 'https://www.mesrs.dz/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.RESEARCH, StudyLevel.PHD],
    fieldsOfStudy: ['Natural Sciences', 'Engineering'],
    hostCountry: 'Algeria',
    region: 'North Africa',
    eligibleNationalities: ['Algeria'],
    openToAllAfrican: false,
    benefits: 'Monthly research stipend for enrolled doctoral researchers.',
    eligibility: 'Algerian nationals enrolled in a recognized doctoral research program.',
    requirements: 'Enrollment certificate, research plan, supervisor endorsement.',
    deadlineAt: days(52),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Uganda Bright Future Scholarship for Girls in STEM',
    slug: 'uganda-bright-future-girls-stem',
    provider: 'Uganda Ministry of Education and Sports',
    officialUrl: 'https://www.education.go.ug/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Engineering', 'Computer Science', 'Mathematics'],
    hostCountry: 'Uganda',
    region: 'East Africa',
    eligibleNationalities: ['Uganda'],
    openToAllAfrican: false,
    benefits: 'Partial tuition support and mentorship for female STEM undergraduates.',
    eligibility: 'Ugandan female students admitted to an accredited STEM degree program.',
    requirements: 'Admission letter, academic transcripts, personal statement.',
    deadlineAt: days(24),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Education and Sports',
    verifiedAt: now,
  },
  {
    title: 'Tanzania Higher Education Students’ Loans Board Grant',
    slug: 'tanzania-heslb-grant',
    provider: 'Higher Education Students’ Loans Board (Tanzania)',
    officialUrl: 'https://www.heslb.go.tz/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Medicine', 'Education', 'Engineering'],
    hostCountry: 'Tanzania',
    region: 'East Africa',
    eligibleNationalities: ['Tanzania'],
    openToAllAfrican: false,
    benefits: 'Combined loan and grant covering tuition and a portion of living costs.',
    eligibility: 'Tanzanian citizens admitted to a priority degree program with demonstrated need.',
    requirements: 'Means assessment form, admission letter, guarantor details.',
    deadlineAt: days(11),
    status: ScholarshipStatus.PUBLISHED,
    source: 'HESLB official site',
    verifiedAt: now,
  },
  {
    title: 'Egypt Ministry of Higher Education Missions Scholarship',
    slug: 'egypt-missions-scholarship',
    provider: 'Egyptian Ministry of Higher Education',
    officialUrl: 'https://www.mohesr.gov.eg/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Medicine', 'Engineering', 'Natural Sciences'],
    hostCountry: 'Egypt',
    region: 'North Africa',
    eligibleNationalities: ['Egypt'],
    openToAllAfrican: false,
    benefits: 'Tuition and a monthly stipend for postgraduate study abroad on return-service terms.',
    eligibility: 'Egyptian nationals employed at a public university with an approved study plan.',
    requirements: 'Employer approval, admission offer, bonded return-service agreement.',
    deadlineAt: days(160),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Stanford University Knight-Hennessy Scholars Program',
    slug: 'stanford-knight-hennessy-scholars',
    provider: 'Stanford University',
    officialUrl: 'https://knight-hennessy.stanford.edu/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United States',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Full tuition, living stipend, and a leadership development program at Stanford.',
    eligibility: 'Admission to any Stanford graduate program combined with demonstrated leadership potential.',
    requirements: 'Stanford graduate admission, three references, leadership essays, interview.',
    deadlineAt: days(130),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Stanford University official site',
    verifiedAt: now,
  },
  {
    title: 'MIT-Africa Postgraduate Research Fellowship',
    slug: 'mit-africa-postgraduate-fellowship',
    provider: 'Massachusetts Institute of Technology',
    officialUrl: 'https://misti.mit.edu/mit-africa',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Engineering', 'Computer Science'],
    hostCountry: 'United States',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Research stipend and travel support for a collaborative project with an MIT lab.',
    eligibility: 'Enrolled graduate students at an African partner university with a faculty-endorsed research proposal.',
    requirements: 'Research proposal, faculty endorsement, CV.',
    deadlineAt: days(4),
    status: ScholarshipStatus.PUBLISHED,
    source: 'MIT-Africa official site',
    verifiedAt: now,
  },
  {
    title: 'University of Toronto International Scholar Award',
    slug: 'university-of-toronto-international-scholar',
    provider: 'University of Toronto',
    officialUrl: 'https://future.utoronto.ca/finances/scholarships/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Canada',
    region: 'North America',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Renewable partial tuition award for incoming international undergraduates.',
    eligibility: 'Admitted international first-year students with an outstanding academic record.',
    requirements: 'University admission, transcripts, no separate application required.',
    deadlineAt: days(175),
    status: ScholarshipStatus.PUBLISHED,
    source: 'University of Toronto official site',
    verifiedAt: now,
  },
  {
    title: 'University of Melbourne Graduate Research Scholarship',
    slug: 'university-of-melbourne-graduate-research',
    provider: 'University of Melbourne',
    officialUrl: 'https://scholarships.unimelb.edu.au/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Environmental Science', 'Public Health'],
    hostCountry: 'Australia',
    region: 'Oceania',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition, health cover, and a living stipend for doctoral researchers.',
    eligibility: 'Admission to a University of Melbourne doctoral program with a qualifying research proposal.',
    requirements: 'Research proposal, academic transcripts, two references.',
    deadlineAt: days(95),
    status: ScholarshipStatus.PUBLISHED,
    source: 'University of Melbourne official site',
    verifiedAt: now,
  },
  {
    title: 'National University of Singapore ASEAN-Africa Scholarship',
    slug: 'nus-asean-africa-scholarship',
    provider: 'National University of Singapore',
    officialUrl: 'https://www.nus.edu.sg/oam/financial-matters/scholarships',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Business', 'Computer Science'],
    hostCountry: 'Singapore',
    region: 'Asia',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Full tuition, accommodation allowance, and a settling-in grant.',
    eligibility: 'Outstanding secondary-school leavers admitted to a qualifying NUS undergraduate program.',
    requirements: 'NUS admission, academic transcripts, interview.',
    deadlineAt: days(58),
    status: ScholarshipStatus.PUBLISHED,
    source: 'National University of Singapore official site',
    verifiedAt: now,
  },
  {
    title: 'Google Africa Developer Scholarship',
    slug: 'google-africa-developer-scholarship',
    provider: 'Google',
    officialUrl: 'https://developers.google.com/programs/africa/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Computer Science'],
    hostCountry: 'Nigeria',
    region: 'West Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Free access to a professional developer certification track and mentorship.',
    eligibility: 'Enrolled students or recent graduates with basic programming knowledge.',
    requirements: 'Online application, coding assessment, commitment to the course schedule.',
    deadlineAt: days(17),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Google Developers official site',
    verifiedAt: now,
  },
  {
    title: 'Mozilla Open Source Support Fellowship',
    slug: 'mozilla-open-source-fellowship',
    provider: 'Mozilla Foundation',
    officialUrl: 'https://foundation.mozilla.org/en/what-we-fund/awards/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.RESEARCH],
    fieldsOfStudy: ['Computer Science'],
    hostCountry: 'Kenya',
    region: 'East Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Project stipend for contributors building open-source tools for internet health.',
    eligibility: 'Applicants proposing an open-source project aligned with Mozilla’s mission.',
    requirements: 'Project proposal, GitHub portfolio, budget outline.',
    deadlineAt: days(-45),
    status: ScholarshipStatus.CLOSED,
    source: 'Mozilla Foundation official site',
    verifiedAt: now,
  },
  {
    title: 'Heriot-Watt University Africa Excellence Bursary',
    slug: 'heriot-watt-africa-excellence-bursary',
    provider: 'Heriot-Watt University',
    officialUrl: 'https://www.hw.ac.uk/uk/students/fees-scholarships.htm',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE, StudyLevel.MASTERS],
    fieldsOfStudy: ['Engineering', 'Business'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Tuition-fee discount for self-funded African applicants.',
    eligibility: 'Applicants holding an unconditional or conditional offer from Heriot-Watt University.',
    requirements: 'University offer letter, no separate application required.',
    deadlineAt: days(29),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Heriot-Watt University official site',
    verifiedAt: now,
  },
  {
    title: 'University of Nairobi Vice-Chancellor’s Award',
    slug: 'university-of-nairobi-vc-award',
    provider: 'University of Nairobi',
    officialUrl: 'https://www.uonbi.ac.ke/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Kenya',
    region: 'East Africa',
    eligibleNationalities: ['Kenya'],
    openToAllAfrican: false,
    benefits: 'One-time cash award recognizing the top-ranked student in each faculty.',
    eligibility: 'Enrolled University of Nairobi students ranked first in their faculty for the academic year.',
    requirements: 'Automatic nomination by faculty; no separate application.',
    deadlineAt: days(110),
    status: ScholarshipStatus.PUBLISHED,
    source: 'University of Nairobi official site',
    verifiedAt: now,
  },
  {
    title: 'Ashesi University Presidential Scholarship',
    slug: 'ashesi-presidential-scholarship',
    provider: 'Ashesi University',
    officialUrl: 'https://www.ashesi.edu.gh/admissions/financial-aid.html',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Computer Science', 'Business', 'Engineering'],
    hostCountry: 'Ghana',
    region: 'West Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Full tuition and accommodation for the duration of the undergraduate program.',
    eligibility: 'Admitted students demonstrating exceptional academic merit and financial need.',
    requirements: 'Ashesi admission, financial aid application, family income documentation.',
    deadlineAt: days(2),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ashesi University official site',
    verifiedAt: now,
  },
  {
    title: 'American University in Cairo Merit Scholarship',
    slug: 'auc-merit-scholarship',
    provider: 'American University in Cairo',
    officialUrl: 'https://www.aucegypt.edu/tuition-and-financial-aid',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Egypt',
    region: 'North Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Renewable partial tuition scholarship based on entering academic record.',
    eligibility: 'Admitted first-year students with a strong secondary-school record.',
    requirements: 'AUC admission, transcripts, standardized test scores.',
    deadlineAt: days(66),
    status: ScholarshipStatus.PUBLISHED,
    source: 'American University in Cairo official site',
    verifiedAt: now,
  },
  {
    title: 'Wits University Postgraduate Merit Award',
    slug: 'wits-postgraduate-merit-award',
    provider: 'University of the Witwatersrand',
    officialUrl: 'https://www.wits.ac.za/study-at-wits/postgraduate/postgraduate-funding/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Natural Sciences', 'Engineering', 'Medicine'],
    hostCountry: 'South Africa',
    region: 'Southern Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Partial tuition remission for high-performing postgraduate applicants.',
    eligibility: 'Applicants with a distinction-level result in their most recent qualification.',
    requirements: 'Academic transcripts, admission offer, research outline (postgraduate research only).',
    deadlineAt: days(37),
    status: ScholarshipStatus.PUBLISHED,
    source: 'University of the Witwatersrand official site',
    verifiedAt: now,
  },
  {
    title: 'Strathmore University Community Service Scholarship',
    slug: 'strathmore-community-service-scholarship',
    provider: 'Strathmore University',
    officialUrl: 'https://www.strathmore.edu/admissions/scholarships/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Business', 'Law', 'Computer Science'],
    hostCountry: 'Kenya',
    region: 'East Africa',
    eligibleNationalities: ['Kenya'],
    openToAllAfrican: false,
    benefits: 'Partial tuition award in exchange for a documented record of community service.',
    eligibility: 'Kenyan applicants with verifiable community service and demonstrated financial need.',
    requirements: 'Community service verification letters, means test, admission letter.',
    deadlineAt: days(13),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Strathmore University official site',
    verifiedAt: now,
  },
  {
    title: 'Bayero University Kano Alumni Endowment Fund',
    slug: 'bayero-university-alumni-endowment',
    provider: 'Bayero University Kano Alumni Association',
    officialUrl: 'https://buk.edu.ng/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Nigeria',
    region: 'West Africa',
    eligibleNationalities: ['Nigeria'],
    openToAllAfrican: false,
    benefits: 'One-off stipend toward tuition and accommodation for continuing students.',
    eligibility: 'Enrolled Bayero University students with at least a second-class-upper average.',
    requirements: 'Result slip, admission letter, bank account details.',
    deadlineAt: days(7),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Bayero University Kano official site',
    verifiedAt: now,
  },
  {
    title: 'Addis Ababa University Graduate Research Assistantship',
    slug: 'addis-ababa-university-research-assistantship',
    provider: 'Addis Ababa University',
    officialUrl: 'https://www.aau.edu.et/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Natural Sciences', 'Agriculture'],
    hostCountry: 'Ethiopia',
    region: 'East Africa',
    eligibleNationalities: ['Ethiopia'],
    openToAllAfrican: false,
    benefits: 'Tuition waiver in exchange for research and teaching assistantship duties.',
    eligibility: 'Admitted graduate students willing to take on assistantship responsibilities.',
    requirements: 'Graduate admission, department assistantship agreement.',
    deadlineAt: days(105),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Addis Ababa University official site',
    verifiedAt: now,
  },
  {
    title: 'Council for Scientific and Industrial Research Studentship',
    slug: 'csir-studentship-south-africa',
    provider: 'Council for Scientific and Industrial Research (South Africa)',
    officialUrl: 'https://www.csir.co.za/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Engineering', 'Natural Sciences'],
    hostCountry: 'South Africa',
    region: 'Southern Africa',
    eligibleNationalities: ['South Africa'],
    openToAllAfrican: false,
    benefits: 'Full tuition plus a monthly stipend tied to a CSIR research project.',
    eligibility: 'South African postgraduate students accepted onto an active CSIR research programme.',
    requirements: 'Research fit assessment, academic transcripts, supervisor interview.',
    deadlineAt: days(42),
    status: ScholarshipStatus.PUBLISHED,
    source: 'CSIR official site',
    verifiedAt: now,
  },
  {
    title: 'Green Climate Fund Readiness Scholars Program',
    slug: 'green-climate-fund-readiness-scholars',
    provider: 'Green Climate Fund',
    officialUrl: 'https://www.greenclimate.fund/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Environmental Studies', 'Environmental Science'],
    hostCountry: 'Rwanda',
    region: 'East Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Partial tuition and a research grant for climate-adaptation focused studies.',
    eligibility: 'Graduate students proposing research directly relevant to African climate adaptation.',
    requirements: 'Research proposal, academic transcripts, letter of support from a host institution.',
    deadlineAt: days(88),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Green Climate Fund official site',
    verifiedAt: now,
  },
  {
    title: 'Bill & Melinda Gates Foundation Discovery Scholars Award',
    slug: 'gates-foundation-discovery-scholars',
    provider: 'Bill & Melinda Gates Foundation',
    officialUrl: 'https://www.gatesfoundation.org/',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Public Health', 'Medicine'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Full tuition, stipend, and research funding for global-health doctoral research.',
    eligibility: 'Admission to a partner university doctoral programme in global or public health.',
    requirements: 'Admission offer, research proposal, three references.',
    deadlineAt: days(155),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Gates Foundation official site',
    verifiedAt: now,
  },
  {
    title: 'Andrew W. Mellon Foundation Humanities Fellowship',
    slug: 'mellon-foundation-humanities-fellowship',
    provider: 'Andrew W. Mellon Foundation',
    officialUrl: 'https://www.mellon.org/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Arts and Humanities', 'Social Sciences'],
    hostCountry: 'South Africa',
    region: 'Southern Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Annual fellowship stipend supporting doctoral humanities research.',
    eligibility: 'Enrolled doctoral candidates researching African humanities or social-science topics.',
    requirements: 'Research proposal, academic transcripts, writing sample.',
    deadlineAt: days(1),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Mellon Foundation official site',
    verifiedAt: now,
  },
  {
    title: 'Cote d’Ivoire National Excellence Scholarship',
    slug: 'cote-divoire-national-excellence-scholarship',
    provider: 'Ivorian Ministry of Higher Education and Scientific Research',
    officialUrl: 'https://www.mesrs.gouv.ci/',
    fundingLevel: FundingLevel.TUITION_ONLY,
    studyLevels: [StudyLevel.UNDERGRADUATE],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'Cote d’Ivoire',
    region: 'West Africa',
    eligibleNationalities: ['Cote d’Ivoire'],
    openToAllAfrican: false,
    benefits: 'Tuition waiver at public universities for top baccalaureate performers.',
    eligibility: 'Ivorian students achieving distinction in the national baccalaureate examination.',
    requirements: 'Baccalaureate results, national ID, university admission confirmation.',
    deadlineAt: days(31),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Ministry of Higher Education official site',
    verifiedAt: now,
  },
  {
    title: 'Aga Khan Foundation International Scholarship',
    slug: 'aga-khan-foundation-international-scholarship',
    provider: 'Aga Khan Foundation',
    officialUrl: 'https://www.akdn.org/how-we-work/akdns-agencies/aga-khan-foundation/aga-khan-foundation-international-scholarship-programme',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Any field'],
    hostCountry: 'United Kingdom',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'A mix of 50% scholarship and 50% loan covering tuition and living costs.',
    eligibility: 'Outstanding students with no other means of financing postgraduate study, from a developing country.',
    requirements: 'Admission offer, financial need documentation, two references.',
    deadlineAt: days(63),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Aga Khan Foundation official site',
    verifiedAt: now,
  },
  {
    title: 'OPEC Fund Scholarship Award',
    slug: 'opec-fund-scholarship-award',
    provider: 'OPEC Fund for International Development',
    officialUrl: 'https://opecfund.org/scholarship-award',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS],
    fieldsOfStudy: ['Economics', 'Public Policy', 'Environmental Studies'],
    hostCountry: 'Austria',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'A one-time award of up to $50,000 toward postgraduate study expenses.',
    eligibility: 'Nationals of OPEC Fund partner countries pursuing a development-relevant master’s degree.',
    requirements: 'Admission offer, academic transcripts, motivation essay on development impact.',
    deadlineAt: days(23),
    status: ScholarshipStatus.PUBLISHED,
    source: 'OPEC Fund official site',
    verifiedAt: now,
  },
  {
    title: 'Open Society Foundations Civil Society Scholar Award',
    slug: 'osf-civil-society-scholar-award',
    provider: 'Open Society Foundations',
    officialUrl: 'https://www.opensocietyfoundations.org/grants/civil-society-scholar-awards',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.PHD, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Social Sciences', 'Law'],
    hostCountry: 'Hungary',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Research stipend supporting scholars whose academic careers were disrupted.',
    eligibility: 'Academics or researchers based at under-resourced universities with an active research plan.',
    requirements: 'Research plan, CV, letter from home institution.',
    deadlineAt: days(-60),
    status: ScholarshipStatus.ARCHIVED,
    source: 'Open Society Foundations official site',
    verifiedAt: now,
  },
  {
    title: 'Carnegie Corporation African Diaspora Fellowship',
    slug: 'carnegie-african-diaspora-fellowship',
    provider: 'Carnegie Corporation of New York',
    officialUrl: 'https://www.iie.org/programs/carnegie-african-diaspora-fellowship-program/',
    fundingLevel: FundingLevel.STIPEND,
    studyLevels: [StudyLevel.RESEARCH],
    fieldsOfStudy: ['Public Health', 'Education', 'Agriculture'],
    hostCountry: 'Ghana',
    region: 'West Africa',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Travel and project stipend for a short-term collaborative teaching or research placement.',
    eligibility: 'Diaspora academics partnering with an African host institution on an approved project.',
    requirements: 'Host institution invitation, project plan, CV.',
    deadlineAt: days(5),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Institute of International Education official site',
    verifiedAt: now,
  },
  {
    title: 'Heinrich Boll Foundation Scholarship for African Students',
    slug: 'heinrich-boll-foundation-scholarship',
    provider: 'Heinrich Böll Foundation',
    officialUrl: 'https://www.boell.de/en/scholarships',
    fundingLevel: FundingLevel.FULL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.PHD],
    fieldsOfStudy: ['Social Sciences', 'Environmental Studies', 'Law'],
    hostCountry: 'Germany',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Monthly stipend, health insurance allowance, and study and travel expenses.',
    eligibility: 'Strong academic record with demonstrated commitment to democracy, human rights, or environmental protection.',
    requirements: 'Academic transcripts, two references, essay on civic engagement.',
    deadlineAt: days(210),
    status: ScholarshipStatus.PUBLISHED,
    source: 'Heinrich Böll Foundation official site',
    verifiedAt: now,
  },
  {
    title: 'Fondation Botnar Digital Health Innovation Grant',
    slug: 'fondation-botnar-digital-health-grant',
    provider: 'Fondation Botnar',
    officialUrl: 'https://www.fondationbotnar.org/',
    fundingLevel: FundingLevel.PARTIAL,
    studyLevels: [StudyLevel.MASTERS, StudyLevel.RESEARCH],
    fieldsOfStudy: ['Public Health', 'Computer Science'],
    hostCountry: 'Switzerland',
    region: 'Europe',
    eligibleNationalities: [],
    openToAllAfrican: true,
    benefits: 'Project grant supporting digital-health research with urban youth populations.',
    eligibility: 'Graduate researchers proposing a digital-health project relevant to youth wellbeing in cities.',
    requirements: 'Project proposal, budget plan, host supervisor letter.',
    deadlineAt: null,
    status: ScholarshipStatus.DRAFT,
    source: 'Fondation Botnar official site',
    verifiedAt: null,
  },
];

async function main() {
  for (const scholarship of scholarships) {
    await db.scholarship.upsert({
      where: { slug: scholarship.slug },
      update: scholarship,
      create: scholarship,
    });
  }
  console.log(`Seeded ${scholarships.length} scholarships.`);

  const adminPasswordHash = await bcrypt.hash(DEV_ADMIN_PASSWORD, 12);
  await db.user.upsert({
    where: { email: DEV_ADMIN_EMAIL },
    update: {},
    create: {
      email: DEV_ADMIN_EMAIL,
      name: 'Bursa Admin',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      onboardedAt: new Date(),
    },
  });
  console.log(`Seeded dev admin: ${DEV_ADMIN_EMAIL} / ${DEV_ADMIN_PASSWORD} (development only)`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
